### ISSUE TITLE
Jobs getting stuck

### ISSUE THREAD

**Issue by torleif** [symbiote/silverstripe-queuedjobs#23]
Every once and a while I get a job that does not finish because of a flakey external API. This job then holds up the queue.

There needs to be a way to force jobs to finish

**Comment by IgorNadj** [comment]
@nyeholt - That's very useful, why is that not the default behaviour for all jobs?

**Comment by nyeholt** [comment]
Originally it was to avoid possible confusion in some older code between what currentStep = 0 (ie unstarted) and currentStep > 0 means (ie job is running). I can't recall the exact scenario off the top of my head though :). What should probably happen is that the queue processor sets the job's current step to 1 (if starting for the first time) immediately after preparing it so that it will be appropriately picked up by the health check.

**Comment by IgorNadj** [comment]
The issue I've run into and why I'm here is that the job data is so big that the process runs out of memory before being able to mark the currentStep as 1, so it never marks the job as broken. Perhaps marking the job as "started" needs to happen much earlier on, in a transactional-block with retrieving the job if possible.

**Comment by nyeholt** [comment]
Is it possible to break the job down into smaller increments so that each call to process() is doing less work each iteration? Trying to restart the job in that scenario may not be ideal if it's dying halfway through processing.

**Comment by assertchris** [comment]
The [new core engine](https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/51) should solve the blocking problem without the work-around... :)

**Comment by robbieaverill** [comment]
Feel free to reopen if this is still a problem in recent versions
